<?php

/**
 * Created by PhpStorm.
 * User: kravchenkov-vv
 * Date: 04.04.17
 * Time: 17:45
 */
class ContactController extends ControllerBase
{

    public function initialize()
    {

        parent::initialize(); // TODO: Change the autogenerated stub
    }


    public function indexAction()
    {

        $users = Users::find(
            [
                "order" => "name",
                "users_active" => "Y"
            ]
        );

        $this->view->user = $users;

    }





}